version: '3.3'

services:
  # Designed to be docker-compose up on client
  amandad:
    build:
      context: .
      dockerfile: client.Dockerfile
      args:
        AMANDA_VERSION: '3.3.9'
    network_mode: "host"
    volumes:
      - amanda_tarlists:/var/lib/amanda/gnutar-lists
    extra_hosts:
      - "amanda_server:192.168.11.11"
    restart: always
    image: andyneff/amanda:client

volumes:
  amanda_tarlists: