version: '3.3'

services:
  # Designed to be docker-compose up on client
  amandad:
    build:
      context: .
      dockerfile: client.Dockerfile
      args:
        AMANDA_VERSION: "${AMANDA_VERSION}"
    image: ${AMANDA_DOCKERHUB_REPO}:client
    network_mode: "host"
    ports:
    - "10080:10080"
    - "10080:10080/udp"
    - "10070-10072:10070-10072"
    - "880:882:880:882"
    - "883:885:883:885/udp"
    volumes:
      - amanda_tarlists:/var/lib/amanda/gnutar-lists
      - /volume2/admin:/admin
      - /volume2/fileserver:/fileserver
    extra_hosts:
      - "amanda-server:${AMANDA_BACKUP_SERVER}"
    restart: always

volumes:
  amanda_tarlists: