version: '3.3'

services:
  # Designed to be docker-compose up on client
  amandad:
    build:
      context: .
      dockerfile: client.Dockerfile
    network_mode: "host"
    extra_hosts:
      - "amanda_server:192.168.11.11"
    image: andyneff/amanda:client
