version: '3.3'

services:
  # Designed to be docker-compose up on client
  amandad:
    build:
      context: .
      dockerfile: client.Dockerfile
      args:
        AMANDA_VERSION: "${AMANDA_VERSION}"
    network_mode: "host"
    volumes:
      - amanda_tarlists:/var/lib/amanda/gnutar-lists
    extra_hosts:
      - "amanda_server:${AMANDA_BACKUP_SERVER}"
    restart: always
    image: ${AMANDA_DOCKERHUB_REPO}:client

volumes:
  amanda_tarlists: