version: '2.0'

services:
  # Designed to be docker-compose up on client
  amandad:
    build:
      context: .
      dockerfile: client.Dockerfile
      args:
        AMANDA_VERSION: "${AMANDA_VERSION}"
    image: ${AMANDA_DOCKERHUB_REPO}:client
    ports:
    - "10070:22"
    volumes:
      - amanda_tarlists:/var/lib/amanda/gnutar-lists
      - amanda_keys:/etc/keys
      - /volume2/admin:/admin
      - /volume2/fileserver:/fileserver
    extra_hosts:
      - "amanda-server:${AMANDA_BACKUP_SERVER}"
    restart: always
    logging:
      driver: "json-file" #I think synology changes the default to db???

volumes:
  amanda_tarlists:
  amanda_keys: