version: '3.3'

services:
  dropbox:
    build:
      context: .
      dockerfile: dropbox.Dockerfile
    hostname: jacquard-dropbox
    volumes:
      - dropbox:/dropbox
      - "amanda-config:/dropbox/Dropbox (VSI)/amanda_etc:ro"

volumes:
  amanda-config:
  amanda-data:
  dropbox:
