version: '3.3'

services:
  amanda:
    build:
      context: .
      dockerfile: recipe_amanda.Dockerfile
      # args:
      #   AMANDA_VERSION: "${AMANDA_VERSION}"
    image: vsiri/recipe:amanda

  gosu:
    build:
      context: .
      dockerfile: recipe_gosu.Dockerfile
      # args:
      #   GOSU_VERSION: "${GOSU_VERSION}"
    image: vsiri/recipe:gosu

  tini:
    build:
      context: .
      dockerfile: recipe_tini.Dockerfile
      # args:
      #   TINI_VERSION: "${TINI_VERSION}"
    image: vsiri/recipe:tini
