version: '3.3'

services:
  # designed to be docker-compose run on server
  server: &server
    build:
      context: .
      dockerfile: server.Dockerfile
      args:
        AMANDA_VERSION: "${AMANDA_VERSION}"
    image: ${AMANDA_DOCKERHUB_REPO}:server
    volumes:
      - /holding:/holding
      - /cache:/cache
      - amanda-config:/etc/amanda/persist/${AMANDA_CONFIG_NAME}
      - amanda-keys:/etc/keys
    devices:
      - "${AMANDA_TAPE_DRIVE}:${AMANDA_TAPE_DRIVE}"
    environment:
      - AMANDA_CONFIG=${AMANDA_CONFIG_NAME}
      - FROM_EMAIL=${AMANDA_FROM_EMAIL}
      - TO_EMAIL=${AMANDA_TO_EMAIL}
      - SMTP_SERVER=${AMANDA_SMTP_SERVER}
      - BACKUP_CLIENTS=${AMANDA_BACKUP_CLIENTS}
      - GNUPGHOME=/etc/keys
    ports:
      - "10070:22"
    hostname: amanda-server

  # Backup
  backup:
    <<: *server
    depends_on:
      - server
    command: ["amdump", "${AMANDA_CONFIG_NAME}"]
  # abort: # does not work, needs to be in the same pid namespace, then it would
  #   <<: *server
  #   command: ["amcleanup", "-k", "${AMANDA_CONFIG_NAME}"]
  cleanup:
    <<: *server
    command: ["amcleanup", "${AMANDA_CONFIG_NAME}"]

  # Checking the tapes
  check:
    <<: *server
    command: ["amcheck", "${AMANDA_CONFIG_NAME}"]
  list:
    <<: *server
    command: ["amtape", "${AMANDA_CONFIG_NAME}", "show"]
  current: #Display current slot/tape
    <<: *server
    command: ["amtape", "${AMANDA_CONFIG_NAME}", "current"]

  # Tape maintenance
  rewind:
    <<: *server
    command: ["mt", "-f", "/dev/nst0", "rewind"]
  eject:
    <<: *server
    command: ["mt-st", "-f", "/dev/nst0", "eject"]

  # Misc
  dump-backup: #Use in conjunction with | tar tv, or | tar xv
    <<: *server
    command: ["amrecover", "/dev/nst0", "-"]
  print-config:
    <<: *server
    command: ["amadmin", "${AMANDA_CONFIG_NAME}", "config"]
#  recover:
#    image: vsiri/amanda:client
#    command: ["amrecover", "${AMANDA_CONFIG_NAME}", "-s", "jacquard"]

volumes:
  amanda-config:
  amanda-keys:
