version: '3.3'

services:
  # designed to be docker-compose run on server
  server: &server
    build:
      context: .
      dockerfile: server.Dockerfile
    image: andyneff/amanda:server
    volumes:
      - /holding:/holding
      - amanda-config:/etc/amanda/vsidata
      - amanda-data:/var/lib/amanda
    devices:
      - "/dev/nst0:/dev/nst0"
    environment:
      - EMAIL_ADDRESS=backup@visionsystemsinc.com
      - EMAIL_SERVER=smtp://smarthost.coxmail.com
    hostname: amanda-server
    container_name: amanda-server
    command: ["bash"]
  eject:
    <<: *server
    command: ["mt-st", "-f", "/dev/nst0", "eject"]
  list:
    <<: *server
    command: ["amtape", "vsidata", "show"]
  check:
    <<: *server
    command: ["amcheck", "vsidata"]
  rewind:
    <<: *server
    command: ["mt", "-f", "/dev/nst0", "rewind"]
  dump-backup: #Use in conjunction with | tar tv, or | tar xv
    <<: *server
    command: ["amrecover", "/dev/nst0", "-"]
  print-config:
    <<: *server
    command: ["amadmin", "vsidata", "config"]
#  recover:
#    image: andyneff/amanda:client
#    command: ["amrecover", "vsidata", "-s", "jacquard"]

volumes:
  amanda-config:
  amanda-data: