version: '3.3'

services:
  # designed to be docker-compose run on server
  server: &server
    build:
      context: .
      dockerfile: server.Dockerfile
    image: andyneff/amanda:server
    volumes:
      - /holding:/holding
      - /cache:/cache
      - amanda-config:/etc/amanda/vsidata
    devices:
      - "/dev/nst0:/dev/nst0"
    environment:
      - FROM_EMAIL=backup@visionsystemsinc.com
      - SMTP_SERVER=smtp://smarthost.coxmail.com
    hostname: amanda-server
    container_name: amanda-server
    command: ["bash"]
  backup:
    <<: *server
    command: ["amdump", "vsidata"]
  abort: # does not work, needs to be in the same pid namespace, then it would
    <<: *server
    command: ["amcleanup", "-k", "vsidata"]
  cleanup:
    <<: *server
    command: ["amcleanup", "vsidata"]
  list:
    <<: *server
    command: ["amtape", "vsidata", "show"]
  check:
    <<: *server
    command: ["amcheck", "vsidata"]
  rewind:
    <<: *server
    command: ["mt", "-f", "/dev/nst0", "rewind"]
  dump-backup: #Use in conjunction with | tar tv, or | tar xv
    <<: *server
    command: ["amrecover", "/dev/nst0", "-"]
  print-config:
    <<: *server
    command: ["amadmin", "vsidata", "config"]
  eject:
    <<: *server
    command: ["mt-st", "-f", "/dev/nst0", "eject"]
  current: #Display current slot/tape
    <<: *server
    command: ["amtape", "vsidata", "current"]
#  recover:
#    image: andyneff/amanda:client
#    command: ["amrecover", "vsidata", "-s", "jacquard"]

volumes:
  amanda-config:
